import { DeletIcon } from "./Icons";

export const shopCategories = [
  {
    title: "Find your perfect vape starter kit now!",
    img: "/assets/images/shop-cat-img-1.png",
    color: "#F2EBD9",
    btn: "Shop Starter Kits",
  },
  {
    title: "Discover your new favorite vape juice now!",
    img: "/assets/images/shop-cat-img-2.png",
    color: "#F4EAEA",
    btn: "Shop Vape Juice",
  },
  {
    title: "Shop you favorite luxury brands now",
    img: "/assets/images/shop-cat-img-3.png",
    color: "#E9ECF4",
    btn: "Shop luxury ",
  },
];

export const hotpromotionsdata = [
  {
    imageURL: "/assets/images/timercard1.png",
  },
  {
    imageURL: "/assets/images/timercard2.png",
  },
  {
    imageURL: "/assets/images/timercard3.png",
  },
];
export const shopCatData = [
  {
    link: "/catalog",
    name: "Starter Kits",
    img: "/assets/images/shop-categories-img-1.png",
    color: "bg-[#F2F0F0]",
  },
  {
    link: "/catalog",
    name: "Disposable Vapes",
    img: "/assets/images/shop-categories-img-2.png",
    color: "bg-[#E9ECF4]",
  },
  {
    link: "/catalog",
    name: "E-Liquid",
    img: "/assets/images/shop-categories-img-3.png",
    color: "bg-[#F4EAEA]",
  },
  {
    link: "/catalog",
    name: "Coils",
    img: "/assets/images/shop-categories-img-4.png",
    color: "bg-[#FD7777]",
  },
  {
    link: "/catalog",
    name: "Batteries & Chargers",
    img: "/assets/images/shop-categories-img-5.png",
    color: "bg-[#F2EBD9]",
  },
  {
    link: "/catalog",
    name: "Tanks",
    img: "/assets/images/shop-categories-img-6.png",
    color: " bg-[#F4EAEA]",
  },
  {
    link: "/catalog",
    name: "Drip tips",
    img: "/assets/images/shop-categories-img-7.png",
    color: "bg-[#F2F0F0]",
  },
  {
    link: "/catalog",
    name: "Luxury ",
    img: "/assets/images/shop-categories-img-8.png",
    color: "bg-[#E9ECF4]",
  },
];
export const vegetablesCategories = [
  {
    title: "Find your perfect vape starter kit now!",
    img: "/assets/images/shop-cat-img-1.png",
    color: "#FFFFFF",
  },
  {
    title: "Discover your new favorite vape juice now! ",
    img: "/assets/images/shop-cat-img-2.png",
    color: "#FFFFFF",
  },
  {
    title: "Shop you favorite luxury brands now",
    img: "/assets/images/shop-cat-img-3.png",
    color: "#FFFFFF",
  },
];

export const popularProducts = [
  {
    banertype: "Sale",
    title: "Xros 2 Pod System",
    productimg: "/assets/images/popular-products-img-4.webp",
    ratingimg: "/assets/images/rating.png",
    ratingvalue: "4",
    bannercolor: "#F2EBD9",
    quantitycheck: "Price per kg",
    oldPrice: "$30.00",
    newPrice: "$24.00",
    liked: false,
    rating: 4,
    slug: "Vaping",
  },
  {
    banertype: "Sale",
    title: "Mega Disposable",
    productimg: "/assets/images/popular-products-img-1.webp",
    ratingimg: "/assets/images/rating.png",
    ratingvalue: "4",
    bannercolor: "#F2EBD9",
    quantitycheck: "Price per kg",
    oldPrice: "$30.00",
    newPrice: "$24.00",
    liked: false,
    rating: 4,
    slug: "Pet Foods",
  },
  {
    banertype: "Sale",
    title: "Nord 2",
    productimg: "/assets/images/popular-products-img-2.webp",
    ratingimg: "/assets/images/rating.png",
    ratingvalue: "4",
    bannercolor: "#F2EBD9",
    quantitycheck: "Price per kg",
    oldPrice: "$70.00",
    newPrice: "$54.00",
    liked: false,
    rating: 4,
    slug: "Pet Foods",
  },
  {
    banertype: "New",
    title: "Novo 3 Kit",
    productimg: "/assets/images/popular-products-img-3.webp",
    ratingimg: "/assets/images/rating.png",
    ratingvalue: "4",
    bannercolor: "#F2EBD9",
    quantitycheck: "Price per kg",
    oldPrice: "$30.00",
    newPrice: "$24.00",
    liked: true,
    rating: 4,
    slug: "Vaping",
  },
  {
    banertype: "Sale",
    title: "Xros 2 Pod System",
    productimg: "/assets/images/popular-products-img-4.webp",
    ratingimg: "/assets/images/rating.png",
    ratingvalue: "4",
    bannercolor: "#F2EBD9",
    quantitycheck: "Price per kg",
    oldPrice: "$30.00",
    newPrice: "$24.00",
    liked: false,
    rating: 4,
    slug: "Vaping",
  },
  {
    banertype: "Sale",
    title: "Mega Disposable",
    productimg: "/assets/images/popular-products-img-1.webp",
    ratingimg: "/assets/images/rating.png",
    ratingvalue: "4",
    bannercolor: "#F2EBD9",
    quantitycheck: "Price per kg",
    oldPrice: "$30.00",
    newPrice: "$24.00",
    liked: false,
    rating: 4,
    slug: "Pet Foods",
  },
  {
    banertype: "Sale",
    title: "Nord 2",
    productimg: "/assets/images/popular-products-img-2.webp",
    ratingimg: "/assets/images/rating.png",
    ratingvalue: "4",
    bannercolor: "#F2EBD9",
    quantitycheck: "Price per kg",
    oldPrice: "$70.00",
    newPrice: "$54.00",
    liked: false,
    rating: 4,
    slug: "Pet Foods",
  },
  {
    banertype: "New",
    title: "Novo 3 Kit",
    productimg: "/assets/images/popular-products-img-3.webp",
    ratingimg: "/assets/images/rating.png",
    ratingvalue: "4",
    bannercolor: "#F2EBD9",
    quantitycheck: "Price per kg",
    oldPrice: "$30.00",
    newPrice: "$24.00",
    liked: true,
    rating: 4,
    slug: "Vaping",
  },
  {
    banertype: "Sale",
    title: "Xros 2 Pod System",
    productimg: "/assets/images/popular-products-img-4.webp",
    ratingimg: "/assets/images/rating.png",
    ratingvalue: "4",
    bannercolor: "#F2EBD9",
    quantitycheck: "Price per kg",
    oldPrice: "$30.00",
    newPrice: "$24.00",
    liked: false,
    rating: 4,
    slug: "Vaping",
  },
  {
    banertype: "Sale",
    title: "Mega Disposable",
    productimg: "/assets/images/popular-products-img-1.webp",
    ratingimg: "/assets/images/rating.png",
    ratingvalue: "4",
    bannercolor: "#F2EBD9",
    quantitycheck: "Price per kg",
    oldPrice: "$30.00",
    newPrice: "$24.00",
    liked: false,
    rating: 4,
    slug: "Pet Foods",
  },
  {
    banertype: "Sale",
    title: "Nord 2",
    productimg: "/assets/images/popular-products-img-2.webp",
    ratingimg: "/assets/images/rating.png",
    ratingvalue: "4",
    bannercolor: "#F2EBD9",
    quantitycheck: "Price per kg",
    oldPrice: "$70.00",
    newPrice: "$54.00",
    liked: false,
    rating: 4,
    slug: "Pet Foods",
  },
  {
    banertype: "New",
    title: "Novo 3 Kit",
    productimg: "/assets/images/popular-products-img-3.webp",
    ratingimg: "/assets/images/rating.png",
    ratingvalue: "4",
    bannercolor: "#F2EBD9",
    quantitycheck: "Price per kg",
    oldPrice: "$30.00",
    newPrice: "$24.00",
    liked: true,
    rating: 4,
    slug: "Vaping",
  },
  {
    banertype: "Sale",
    title: "Xros 2 Pod System",
    productimg: "/assets/images/popular-products-img-4.webp",
    ratingimg: "/assets/images/rating.png",
    ratingvalue: "4",
    bannercolor: "#F2EBD9",
    quantitycheck: "Price per kg",
    oldPrice: "$30.00",
    newPrice: "$24.00",
    liked: false,
    rating: 4,
    slug: "Vaping",
  },
  {
    banertype: "Sale",
    title: "Mega Disposable",
    productimg: "/assets/images/popular-products-img-1.webp",
    ratingimg: "/assets/images/rating.png",
    ratingvalue: "4",
    bannercolor: "#F2EBD9",
    quantitycheck: "Price per kg",
    oldPrice: "$30.00",
    newPrice: "$24.00",
    liked: false,
    rating: 4,
    slug: "Pet Foods",
  },
];

export const popularProductsCategory = [
  {
    id: "1",
    category: "All",
  },
  {
    id: "2",
    category: "E-liquid",
  },
  {
    id: "3",
    category: "Disposable vapes",
  },
  {
    id: "4",
    category: "Tanks",
  },
  {
    id: "5",
    category: "Luxury",
  },
];

export const productsWithDeliverylist = [
  {
    title: "Vaps",
  },
  {
    title: "Tanks",
  },
  {
    title: "Dried Vaping",
  },
  {
    title: "Drinks",
  },
  {
    title: "Drinks",
  },
  {
    title: "Vapings",
  },
];
export const productsWithDeliverydesc = [
  {
    title:
      "Another highlight of is the opportunity to buy exotic Vaping. Our assortment includes more than 500 exotic Vaping from different parts of the world. It is difficult to buy them in a regular supermarket. However, using our delivery, you can easily feel the exotic taste.",
  },
  {
    title:
      "Looking for an original gift for a loved one, friend or colleague? In our online grocery store you can order Box - a set of exotic Vaping in a beautiful craft box. Such a gift will be remembered for a long time and will cause pleasant emotions and impressions of new tastes. In addition, you can assemble and buy such a set yourself by choosing any Vaping, berries or nuts from the assortment.",
  },
  {
    title:
      "The high quality of our products is confirmed by relevant certificates and the international HACCP certificate. We make sure that customers receive only selected natural products, ready to use. They are stored in our own warehouses where the correct temperature is maintained to keep them fresh and ripe.",
  },
];
export const topSellingsdata = [
  {
    img: "/assets/images/blog-img-3.png",
    title: "Product name",
    text: "Additional text",
    price: "$24.00  ",
    delPrice: "$30.00",
  },
  {
    img: "/assets/images/blog-img-2.png",
    title: "Product name",
    text: "Additional text",
    price: "$24.00  ",
    delPrice: "$30.00",
  },
  {
    img: "/assets/images/blog-img-1.png",
    title: "Product name",
    text: "Additional text",
    price: "$24.00  ",
    delPrice: "$30.00",
  },
];

export const latestpostsdata = [
  {
    img: "/assets/images/selling-img-1.png",
    title: "Sticky Ginger Rice Bowls",
    date: "June 22, 2022",
  },
  {
    img: "/assets/images/selling-img-2.png",
    title: "Sticky Ginger Rice Bowls",
    date: "June 22, 2022",
  },
  {
    img: "/assets/images/selling-img-3.png",
    title: "Sticky Ginger Rice Bowls",
    date: "June 22, 2022",
  },
];

export const tabledata = [
  {
    img: "/assets/images/table1.png",
    title: "Garbuz Ukraine",
    category: "Vapings ",
    weight: "1 kg",
    price: "$24.00",
    delPrice: "$30.00",
    deletIcon: <DeletIcon />,
  },
  {
    img: "/assets/images/table2.png",
    title: "Garbuz Ukraine",
    category: "Vapings ",
    weight: "1 kg",
    price: "$24.00",
    delPrice: "$30.00",
    deletIcon: <DeletIcon />,
  },
  {
    img: "/assets/images/table3.png",
    title: "Garbuz Ukraine",
    category: "Vapings ",
    weight: "1 kg",
    price: "$24.00",
    delPrice: "$30.00",
    deletIcon: <DeletIcon />,
  },
];
export const fruitsProducts = [
  {
    title: "This is a great remedy for those who suffer from constipation.",
  },
  {
    title: "Figs can increase hemoglobin if eaten regularly.",
  },
  {
    title:
      "Elimination of toxins and normalization of digestion leads to weight loss.",
  },
];

export const catalogproductsdata = [
  {
    banertype: "New",
    title: "Garbuz Ukraine",
    productimg: "/assets/images/catlog-img-1.png",
    ratingimg: "/assets/images/rating.png",
    ratingvalue: "4",
    bannercolor: "#F2EBD9",
    quantitycheck: "Price per kg",
    oldPrice: "$30.00",
    newPrice: "$24.00",
    color: "bg-[#67BCEE]",
    liked: false,
  },
  {
    banertype: "",
    title: "Ground allspice",
    productimg: "/assets/images/catlog-img-2.png",
    ratingimg: "/assets/images/rating.png",
    ratingvalue: "4",
    bannercolor: "#F2EBD9",
    quantitycheck: "Price per kg",
    oldPrice: "$30.00",
    newPrice: "$24.00",
    color: "bg-[#27CA7D]",
    liked: true,
  },
  {
    banertype: "Hot",
    title: "Wash the carrot",
    productimg: "/assets/images/catlog-img-3.png",
    ratingimg: "/assets/images/rating.png",
    ratingvalue: "4",
    bannercolor: "#F2EBD9",
    quantitycheck: "Price per kg",
    oldPrice: "$30.00",
    newPrice: "$24.00",
    color: "bg-[]",
    liked: true,
  },
  {
    banertype: "Hot",
    title: "Boston",
    productimg: "/assets/images/catlog-img-4.png",
    ratingimg: "/assets/images/rating.png",
    ratingvalue: "4",
    bannercolor: "#F2EBD9",
    quantitycheck: "Price per kg",
    oldPrice: "$30.00",
    newPrice: "$24.00",
    color: "bg-[#F74B81]",
    liked: true,
  },
  {
    banertype: "Sale",
    title: "Petya Zhovta",
    productimg: "/assets/images/catlog-img-5.png",
    ratingimg: "/assets/images/rating.png",
    ratingvalue: "4",
    bannercolor: "#F2EBD9",
    quantitycheck: "Price per kg",
    oldPrice: "$30.00",
    newPrice: "$24.00",
    color: "bg-[]",
    liked: true,
  },
  {
    banertype: "",
    title: "Boby Edamame c/m",
    productimg: "/assets/images/catlog-img-6.png",
    ratingimg: "/assets/images/rating.png",
    ratingvalue: "4",
    bannercolor: "#F2EBD9",
    quantitycheck: "Price per kg",
    oldPrice: "$30.00",
    newPrice: "$24.00",
    color: "bg-[#F74B81]",
    liked: true,
  },
  {
    banertype: "",
    title: "Kiwi Gold",
    productimg: "/assets/images/catlog-img-7.png",
    ratingimg: "/assets/images/rating.png",
    ratingvalue: "4",
    bannercolor: "#F2EBD9",
    quantitycheck: "Price per kg",
    oldPrice: "$30.00",
    newPrice: "$24.00",
    color: "bg-[#67BCEE]",
    liked: false,
  },
  {
    banertype: "",
    title: "Mushroom Shiitake",
    productimg: "/assets/images/catlog-img-8.png",
    ratingimg: "/assets/images/rating.png",
    ratingvalue: "4",
    bannercolor: "#F2EBD9",
    quantitycheck: "Price per kg",
    oldPrice: "$30.00",
    newPrice: "$24.00",
    color: "bg-[#27CA7D]",
    liked: true,
  },
  {
    banertype: "New",
    title: "Garbuz Ukraine",
    productimg: "/assets/images/catlog-img-9.png",
    ratingimg: "/assets/images/rating.png",
    ratingvalue: "4",
    bannercolor: "#F2EBD9",
    quantitycheck: "Price per kg",
    oldPrice: "$30.00",
    newPrice: "$24.00",
    color: "bg-[#67BCEE]",
    liked: false,
  },
  {
    banertype: "Sale",
    title: "Ground allspice",
    productimg: "/assets/images/catlog-img-10.png",
    ratingimg: "/assets/images/rating.png",
    ratingvalue: "4",
    bannercolor: "#F2EBD9",
    quantitycheck: "Price per kg",
    oldPrice: "$30.00",
    newPrice: "$24.00",
    color: "bg-[#27CA7D]",
    liked: true,
  },
  {
    banertype: " ",
    title: "Wash the carrot",
    productimg: "/assets/images/catlog-img-11.png",
    ratingimg: "/assets/images/rating.png",
    ratingvalue: "4",
    bannercolor: "#F2EBD9",
    quantitycheck: "Price per kg",
    oldPrice: "$30.00",
    newPrice: "$24.00",
    color: "bg-[]",
    liked: true,
  },
  {
    banertype: "Hot",
    title: "Boston",
    productimg: "/assets/images/catlog-img-12.png",
    ratingimg: "/assets/images/rating.png",
    ratingvalue: "4",
    bannercolor: "#F2EBD9",
    quantitycheck: "Price per kg",
    oldPrice: "$30.00",
    newPrice: "$24.00",
    color: "bg-[#F74B81]",
    liked: true,
  },
  {
    banertype: "Hot",
    title: "Petya Zhovta",
    productimg: "/assets/images/catlog-img-13.png",
    ratingimg: "/assets/images/rating.png",
    ratingvalue: "4",
    bannercolor: "#F2EBD9",
    quantitycheck: "Price per kg",
    oldPrice: "$30.00",
    newPrice: "$24.00",
    color: "bg-[]",
    liked: true,
  },
  {
    banertype: "Sale",
    title: "Boby Edamame c/m",
    productimg: "/assets/images/catlog-img-14.png",
    ratingimg: "/assets/images/rating.png",
    ratingvalue: "4",
    bannercolor: "#F2EBD9",
    quantitycheck: "Price per kg",
    oldPrice: "$30.00",
    newPrice: "$24.00",
    color: "bg-[#F74B81]",
    liked: true,
  },
  {
    banertype: "",
    title: "Kiwi Gold",
    productimg: "/assets/images/catlog-img-15.png",
    ratingimg: "/assets/images/rating.png",
    ratingvalue: "4",
    bannercolor: "#F2EBD9",
    quantitycheck: "Price per kg",
    oldPrice: "$30.00",
    newPrice: "$24.00",
    color: "bg-[#67BCEE]",
    liked: false,
  },
];
export const reviewsdata = [
  {
    img: "/assets/images/reviews-img-user.png",
    name: "Marina",
    time: "December 4, 2022 at 3:12 pm",
    desc: "“They keep you informed throughout and make sure that you get the loan to suit your individual needs. Don't waste your time going anywhere else.” “They keep you informed throughout and make sure that you get the loan to suit your individual needs. Don't waste your time going anywhere else.”",
  },
  {
    img: "/assets/images/reviews-img-user.png",
    name: "Marina",
    time: "December 4, 2022 at 3:12 pm",
    desc: "“They keep you informed throughout and make sure that you get the loan to suit your individual needs. Don't waste your time going anywhere else.” “They keep you informed throughout and make sure that you get the loan to suit your individual needs. Don't waste your time going anywhere else.”",
  },
  {
    img: "/assets/images/reviews-img-user.png",
    name: "Misha",
    time: "December 4, 2022 at 3:12 pm",
    desc: "“They keep you informed throughout and make sure that you get the loan to suit your individual needs. Don't waste your time going anywhere else.” “They keep you informed throughout and make sure that you get the loan to suit your individual needs. Don't waste your time going anywhere else.”",
  },
];
export const faqData = [
  {
    questions: "What is Your Product Quality?",
    answer: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam at diam leo. Mauris a ante placerat, dignissim orci eget, viverra ante. Mauris ornare pellentesque augue. Curabitur leo nibh, ultrices vel ultricies eu, vulputate at felis.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam at diam leo. Mauris a ante placerat, dignissim orci eget, viverra ante. Mauris ornare pellentesque augue. Curabitur leo nibh, ultrices vel ultricies eu, vulputate at felis.`,
  },
  {
    questions: "What is Your Product Quality?",
    answer: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam at diam leo. Mauris a ante placerat, dignissim orci eget, viverra ante. Mauris ornare pellentesque augue. Curabitur leo nibh, ultrices vel ultricies eu, vulputate at felis.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam at diam leo. Mauris a ante placerat, dignissim orci eget, viverra ante. Mauris ornare pellentesque augue. Curabitur leo nibh, ultrices vel ultricies eu, vulputate at felis.`,
  },
  {
    questions: "What Shipping Methods Are Available?",
    answer: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam at diam leo. Mauris a ante placerat, dignissim orci eget, viverra ante. Mauris ornare pellentesque augue. Curabitur leo nibh, ultrices vel ultricies eu, vulputate at felis.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam at diam leo. Mauris a ante placerat, dignissim orci eget, viverra ante. Mauris ornare pellentesque augue. Curabitur leo nibh, ultrices vel ultricies eu, vulputate at felis.`,
  },
  {
    questions: "What Payment Methods Are Accepted?",
    answer: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam at diam leo. Mauris a ante placerat, dignissim orci eget, viverra ante. Mauris ornare pellentesque augue. Curabitur leo nibh, ultrices vel ultricies eu, vulputate at felis.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam at diam leo. Mauris a ante placerat, dignissim orci eget, viverra ante. Mauris ornare pellentesque augue. Curabitur leo nibh, ultrices vel ultricies eu, vulputate at felis.`,
  },
  {
    questions: "How Do I Place an Order?",
    answer: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam at diam leo. Mauris a ante placerat, dignissim orci eget, viverra ante. Mauris ornare pellentesque augue. Curabitur leo nibh, ultrices vel ultricies eu, vulputate at felis.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam at diam leo. Mauris a ante placerat, dignissim orci eget, viverra ante. Mauris ornare pellentesque augue. Curabitur leo nibh, ultrices vel ultricies eu, vulputate at felis.`,
  },
  {
    questions: "How Do I Pay?",
    answer: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam at diam leo. Mauris a ante placerat, dignissim orci eget, viverra ante. Mauris ornare pellentesque augue. Curabitur leo nibh, ultrices vel ultricies eu, vulputate at felis.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam at diam leo. Mauris a ante placerat, dignissim orci eget, viverra ante. Mauris ornare pellentesque augue. Curabitur leo nibh, ultrices vel ultricies eu, vulputate at felis.`,
  },
  {
    questions: "Will the Vapings Be Fresh?",
    answer: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam at diam leo. Mauris a ante placerat, dignissim orci eget, viverra ante. Mauris ornare pellentesque augue. Curabitur leo nibh, ultrices vel ultricies eu, vulputate at felis.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam at diam leo. Mauris a ante placerat, dignissim orci eget, viverra ante. Mauris ornare pellentesque augue. Curabitur leo nibh, ultrices vel ultricies eu, vulputate at felis.`,
  },
  {
    questions: "Can I Order Over Phone?",
    answer: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam at diam leo. Mauris a ante placerat, dignissim orci eget, viverra ante. Mauris ornare pellentesque augue. Curabitur leo nibh, ultrices vel ultricies eu, vulputate at felis.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam at diam leo. Mauris a ante placerat, dignissim orci eget, viverra ante. Mauris ornare pellentesque augue. Curabitur leo nibh, ultrices vel ultricies eu, vulputate at felis.`,
  },
];
export const recipsarticlesdata = [
  {
    img: "/assets/images/recips-articles-img-1.png",
    category: "Category",
    time: "June 22, 2022",
    title: "We Always Ready to Give You Best Delivery Support",
    desc: "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.",
    userImg: "/assets/images/recips-user-img-1.png",
    userName: "Darlene Robertson",
  },
  {
    img: "/assets/images/recips-articles-img-2.png",
    category: "Category",
    time: "June 22, 2022",
    title: "We Always Ready to Give You Best Delivery Support",
    desc: "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.",
    userImg: "/assets/images/recips-user-img-1.png",
    userName: "Darlene Robertson",
  },
  {
    img: "/assets/images/recips-articles-img-3.png",
    category: "Category",
    time: "June 22, 2022",
    title: "We Always Ready to Give You Best Delivery Support",
    desc: "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.",
    userImg: "/assets/images/recips-user-img-1.png",
    userName: "Darlene Robertson",
  },
  {
    img: "/assets/images/recips-articles-img-4.png",
    category: "Category",
    time: "June 22, 2022",
    title: "We Always Ready to Give You Best Delivery Support",
    desc: "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.",
    userImg: "/assets/images/recips-user-img-1.png",
    userName: "Darlene Robertson",
  },
  {
    img: "/assets/images/recips-articles-img-5.png",
    category: "Category",
    time: "June 22, 2022",
    title: "We Always Ready to Give You Best Delivery Support",
    desc: "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.",
    userImg: "/assets/images/recips-user-img-1.png",
    userName: "Darlene Robertson",
  },
  {
    img: "/assets/images/recips-articles-img-6.png",
    category: "Category",
    time: "June 22, 2022",
    title: "We Always Ready to Give You Best Delivery Support",
    desc: "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.",
    userImg: "/assets/images/recips-user-img-1.png",
    userName: "Darlene Robertson",
  },
  {
    img: "/assets/images/recips-articles-img-3.png",
    category: "Category",
    time: "June 22, 2022",
    title: "We Always Ready to Give You Best Delivery Support",
    desc: "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.",
    userImg: "/assets/images/recips-user-img-1.png",
    userName: "Darlene Robertson",
  },
  {
    img: "/assets/images/recips-articles-img-2.png",
    category: "Category",
    time: "June 22, 2022",
    title: "We Always Ready to Give You Best Delivery Support",
    desc: "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.",
    userImg: "/assets/images/recips-user-img-1.png",
    userName: "Darlene Robertson",
  },
  {
    img: "/assets/images/recips-articles-img-1.png",
    category: "Category",
    time: "June 22, 2022",
    title: "We Always Ready to Give You Best Delivery Support",
    desc: "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.",
    userImg: "/assets/images/recips-user-img-1.png",
    userName: "Darlene Robertson",
  },
  {
    img: "/assets/images/recips-articles-img-4.png",
    category: "Category",
    time: "June 22, 2022",
    title: "We Always Ready to Give You Best Delivery Support",
    desc: "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.",
    userImg: "/assets/images/recips-user-img-1.png",
    userName: "Darlene Robertson",
  },
  {
    img: "/assets/images/recips-articles-img-5.png",
    category: "Category",
    time: "June 22, 2022",
    title: "We Always Ready to Give You Best Delivery Support",
    desc: "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.",
    userImg: "/assets/images/recips-user-img-1.png",
    userName: "Darlene Robertson",
  },
  {
    img: "/assets/images/recips-articles-img-6.png",
    category: "Category",
    time: "June 22, 2022",
    title: "We Always Ready to Give You Best Delivery Support",
    desc: "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.",
    userImg: "/assets/images/recips-user-img-1.png",
    userName: "Darlene Robertson",
  },
];

export const whatweprovidecarddata = [
  {
    imageURL: "/assets/images/best-prices-and-offer.png",
    heading: "Best Prices & Offers",
    description: `There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form`,
  },
  {
    imageURL: "/assets/images/wide-assortment-img.png",
    heading: "Wide Assortment",
    description: `There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form`,
  },
  {
    imageURL: "/assets/images/free-delivery-img.png",
    heading: "Free Delivery",
    description: `There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form`,
  },
  {
    imageURL: "/assets/images/easy-returns-img.png",
    heading: "Easy Returns",
    description: `There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form`,
  },
  {
    imageURL: "/assets/images/100per-satisfaction.png",
    heading: "100% Satisfaction",
    description: `There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form`,
  },
  {
    imageURL: "/assets/images/great-daily-deal.png",
    heading: "Great Daily Deal",
    description: `There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form`,
  },
];
export const ourteamdata = [
  {
    img: "/assets/images/team1.png",
    name: "Esther Howard",
    rank: "Manager",
  },
  {
    img: "/assets/images/team2.png",
    name: "Esther Howard",
    rank: "Manager",
  },
  {
    img: "/assets/images/team3.png",
    name: "Esther Howard",
    rank: "Manager",
  },
  {
    img: "/assets/images/team4.png",
    name: "Esther Howard",
    rank: "Manager",
  },
  {
    img: "/assets/images/team5.png",
    name: "Esther Howard",
    rank: "Manager",
  },
  {
    img: "/assets/images/team6.png",
    name: "Esther Howard",
    rank: "Manager",
  },
  {
    img: "/assets/images/team7.png",
    name: "Esther Howard",
    rank: "Manager",
  },
  {
    img: "/assets/images/team8.png",
    name: "Esther Howard",
    rank: "Manager",
  },
];

export const footerlinksdata = [
  { name: "Beans", link: "/beans" },
  { name: "Carrots", link: "/carrots" },
  { name: "Vaping", link: "/Vaping" },
  { name: "Garlic", link: "/garlic" },
  { name: "Mushrooms", link: "/mushrooms" },
  { name: "E-liquid", link: "/E-liquid" },
  { name: "Chilli peppers", link: "/chilli-peppers" },
  { name: "Broccoli", link: "/broccoli" },
  { name: "SKE-Vaping", link: "/ske-Vaping" },
  { name: "Cherries", link: "/cherries" },
  { name: "Vaping", link: "/vaping" },
  { name: "Seo tag", link: "/seo-tag" },
  { name: "Vapinng", link: "/vapinng" },
  { name: "Seo tag", link: "/seo-tag" },
  { name: "vaping", link: "/Vaping-ske" },
  { name: "IVG-vaping", link: "/ivg-vaping" },
];

export const heroSliderData = [
  {
    title: "Luxury vapes",
    img: "/assets/images/hero-img-1.png",
    offer: "Up to 30% off your first order",
  },
  {
    title: "Luxury vapes",
    img: "/assets/images/hero-img-1.png",
    offer: "Up to 30% off your first order",
  },
  {
    title: "Luxury vapes",
    img: "/assets/images/hero-img-1.png",
    offer: "Up to 30% off your first order",
  },
];

export const relatedProductsData = [
  {
    img: "/assets/images/popular-products-img-1.webp",
    category: "Category",
    productName: "Garbuz Ukraine",
    prKg: "Price per kg",
    price: "$24.00",
    delPrice: "$30.00",
    banertype: "Sale",
  },
  {
    img: "/assets/images/popular-products-img-2.webp",
    category: "Category",
    productName: "Garbuz Ukraine",
    prKg: "Price per kg",
    price: "$24.00",
    delPrice: "$30.00",
    banertype: "New",
  },
  {
    img: "/assets/images/popular-products-img-3.webp",
    category: "Category",
    productName: "Garbuz Ukraine",
    prKg: "Price per kg",
    price: "$24.00",
    delPrice: "$30.00",
    banertype: "",
  },
  {
    img: "/assets/images/popular-products-img-4.webp",
    category: "Category",
    productName: "Garbuz Ukraine",
    prKg: "Price per kg",
    price: "$24.00",
    delPrice: "$30.00",
    banertype: "Hot",
  },
  {
    img: "/assets/images/popular-products-img-1.webp",
    category: "Category",
    productName: "Garbuz Ukraine",
    prKg: "Price per kg",
    price: "$24.00",
    delPrice: "$30.00",
    banertype: "Hot",
  },
];
export const promotionalGoodData = [
  {
    img: "/assets/images/popular-products-img-6.webp",
    category: "Category",
    productName: "Boston",
    prKg: "Price per kg",
    price: "$24.00 ",
    delPrice: "$30.00",
    banertype: "-5%",
  },
  {
    img: "/assets/images/popular-products-img-7.webp",
    category: "Category",
    productName: "Boston",
    prKg: "Price per kg",
    price: "$24.00 ",
    delPrice: "$30.00",
    banertype: "-5%",
  },
  {
    img: "/assets/images/popular-products-img-8.webp",
    category: "Category",
    productName: "Boston",
    prKg: "Price per kg",
    price: "$24.00 ",
    delPrice: "$30.00",
    banertype: "-5%",
  },
  {
    img: "/assets/images/popular-products-img-9.webp",
    category: "Category",
    productName: "Boston",
    prKg: "Price per kg",
    price: "$24.00 ",
    delPrice: "$30.00",
    banertype: "-5%",
  },
];
export const dailyBestSellsData = [
  {
    img: "/assets/images/popular-products-img-8.webp",
    category: "Category",
    productName: "Monster Bars 3500",
    prKg: "Price per kg",
    price: "$24.00 ",
    delPrice: "$30.00",
    banertype: "New",
  },
  {
    img: "/assets/images/popular-products-img-5.webp",
    category: "Category",
    productName: "Boston",
    prKg: "Price per kg",
    price: "$24.00 ",
    delPrice: "$30.00",
    banertype: "",
  },
  {
    img: "/assets/images/popular-products-img-9.webp",
    category: "Category",
    productName: "Nord 4 80W Pod Kit",
    prKg: "Price per kg",
    price: "$24.00 ",
    delPrice: "$30.00",
    banertype: "Hot",
  },
  {
    img: "/assets/images/popular-products-img-7.webp",
    category: "Category",
    productName: "Boston",
    prKg: "Price per kg",
    price: "$24.00",
    delPrice: "$30.00",
    banertype: "",
  },
];
export const blogsidedata = [
  {
    tital: "  Salat is kinda good start to your morning routines",
    img: "/assets/images/blog-img-1.png",
    date: "17. 6. 2020",
    name: "Author",
  },
  {
    tital: "  Salat is kinda good start to your morning routines",
    img: "/assets/images/blog-img-2.png",
    date: "17. 6. 2020",
    name: "Author",
  },
  {
    tital: "  Salat is kinda good start to your morning routines",
    img: "/assets/images/blog-img-3.png",
    date: "17. 6. 2020",
    name: "Author",
  },
];
